name: consolelog
description: Affrordable debug.
version: 0.0.2
homepage: https://github.com/la-only/consolelog

environment:
  sdk: '>=2.14.4 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
